### ISSUE TITLE
Document parsing changes in RF 3.2

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3293]
New parser in RF 3.2 (#3076) changes parsing in many ways and these changes need to be documented in the User Guide as well as in the API docs. This issue covers documentation updates and related issues can be closed when they are otherwise ready.

- [ ] HTML/TSV formats are not supported anymore (#3081)
- [ ] Only `*.robot` files are parsed by default (#3084)
- [ ] Whitespace handling changes (#3121)
- [x] Docs for the new stable parsing APIs (#3373)
- [x] Tidy changes
    - [x] UG
    - [x] --help
